name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    environment: myenvironment
    env:
       key1 : '${{ secrets.CONNECTION_STRING }}'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: SmallRatings
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: echoeing
      run: echo ${{env.key1}}
