name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish:
    environment: myenvironment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: SmallRatings
      env:
         key1 : ${{ secrets.TESTSECRET }}
      run: echo ${env.key1}
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
